### ISSUE TITLE
Crash on Android O

### ISSUE THREAD

**Issue by garvankeeley** [mcomella/FirefoxAccounts-android#27]
I am getting a crash on Android O (I can add more info as to the exact version).
This is after pulling master and running the default config sample app.
Is there more investigation I could do here to help?
```
FATAL EXCEPTION: main
                                                                        Process: org.mozilla.sync.example, PID: 4879
                                                                        java.lang.SecurityException: Signature check failed for org.mozilla.sync.example
                                                                            at android.os.Parcel.readException(Parcel.java:1915)
                                                                            at android.os.Parcel.readException(Parcel.java:1861)
                                                                            at com.google.android.gms.common.internal.zzv$zza$zza.zza(Unknown Source:41)
                                                                            at com.google.android.gms.common.internal.zzf.zza(Unknown Source:0)
                                                                            at com.google.android.gms.internal.zzzf$zzc.zzxQ(Unknown Source:0)
                                                                            at com.google.android.gms.internal.zzzf$zzf.run(Unknown Source:0)
                                                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                            at com.google.android.gms.internal.zzabx.run(Unknown Source:7)
                                                                            at java.lang.Thread.run(Thread.java:764)
```

**Comment by garvankeeley** [comment]
I am only half-paying-attention while I playing around with this, now that I read that the stack trace is `Signature check failed` seems like it could be an install issue that perhaps I have caused, closing while I research...
